# Generated by Django 4.2 on 2023-05-14 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='if_profile_verified',
            new_name='if_verified',
        ),
    ]
