# Generated by Django 4.2 on 2023-05-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_birth_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='if_verified',
            new_name='is_verified',
        ),
    ]
