# Generated by Django 4.2 on 2023-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_rename_if_verified_customuser_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, verbose_name="Last name"),
        ),
    ]
