# Generated by Django 4.2 on 2023-05-13 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Горячие напитки', 'Горячие напитки'), ('Холодные напитки', 'Холодные напитки'), ('Алкогольные напитки', 'Алкогольные напитки')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('category', models.CharField(choices=[('Пицца', 'Пицца'), ('Суши', 'Суши'), ('Плов', 'Плов'), ('Шашлык', 'Шашлык')])),
                ('sause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sause')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
