# Generated by Django 4.2 on 2023-05-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_drink_food_rename_sause_sauce_delete_drinkmenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='liter',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Burger', 'Burger'), ('Twister', 'Twister'), ('Bucket', 'Bucket')]),
        ),
    ]
