# Generated by Django 4.2 on 2023-05-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_drink_liter_alter_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='spicy',
            field=models.BooleanField(default=False),
        ),
    ]
