# Generated by Django 4.2 on 2023-05-23 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_boxmix_delete_icecream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxmix',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.dessert'),
        ),
        migrations.AlterField(
            model_name='boxmix',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.drink'),
        ),
        migrations.AlterField(
            model_name='boxmix',
            name='sauce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.sauce'),
        ),
    ]
