# Generated by Django 4.2 on 2023-05-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_boxmix_dessert_alter_boxmix_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxmix',
            name='dessert',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.dessert'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boxmix',
            name='drink',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.drink'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boxmix',
            name='sauce',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.sauce'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dessert',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
