# Generated by Django 4.2 on 2023-05-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_boxmix_on_stop_dessert_on_stop_drink_on_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxmix',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eda', to='app.food'),
        ),
    ]
