# Generated by Django 4.2 on 2023-05-25 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_boxmix_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.IntegerField(default=0)),
                ('on_stop', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='dessert',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dessert',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dessert',
            name='on_stop',
        ),
        migrations.RemoveField(
            model_name='dessert',
            name='price',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='id',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='on_stop',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='price',
        ),
        migrations.RemoveField(
            model_name='food',
            name='id',
        ),
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='on_stop',
        ),
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sauce',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sauce',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sauce',
            name='on_stop',
        ),
        migrations.RemoveField(
            model_name='sauce',
            name='price',
        ),
        migrations.AddField(
            model_name='dessert',
            name='dishmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.dishmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='dishmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.dishmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='dishmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.dishmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sauce',
            name='dishmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.dishmodel'),
            preserve_default=False,
        ),
    ]
