# Generated by Django 4.2 on 2023-05-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_dishmodel_remove_dessert_id_remove_dessert_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoxMix',
        ),
    ]
