# Generated by Django 4.2 on 2023-05-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_boxmix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BoxMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('on_stop', models.BooleanField(default=False)),
                ('dessert', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.dessert')),
                ('drink', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.drink')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.food')),
                ('sauce', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.sauce')),
            ],
        ),
    ]
