# Generated by Django 4.2 on 2023-05-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_dishmodel_dish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxmix',
            old_name='dessert',
            new_name='box_dessert',
        ),
        migrations.RenameField(
            model_name='boxmix',
            old_name='drink',
            new_name='box_drink',
        ),
        migrations.RenameField(
            model_name='boxmix',
            old_name='food',
            new_name='box_food',
        ),
        migrations.RenameField(
            model_name='boxmix',
            old_name='sauce',
            new_name='box_sauce',
        ),
        migrations.RemoveField(
            model_name='boxmix',
            name='id',
        ),
        migrations.RemoveField(
            model_name='boxmix',
            name='name',
        ),
        migrations.RemoveField(
            model_name='boxmix',
            name='on_stop',
        ),
        migrations.AddField(
            model_name='boxmix',
            name='dish_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.dish'),
            preserve_default=False,
        ),
    ]
