# Generated by Django 4.2 on 2023-05-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_boxmix_box_dessert_alter_boxmix_box_drink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
