# Generated by Django 4.2 on 2023-05-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxmix',
            name='box_dessert',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.dessert'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boxmix',
            name='box_drink',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.drink'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boxmix',
            name='box_sauce',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.sauce'),
            preserve_default=False,
        ),
    ]
