# Generated by Django 4.2 on 2023-05-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_boxmix_box_dessert_alter_boxmix_box_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxmix',
            name='box_dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.dessert'),
        ),
        migrations.AlterField(
            model_name='boxmix',
            name='box_drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.drink'),
        ),
        migrations.AlterField(
            model_name='boxmix',
            name='box_sauce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.sauce'),
        ),
    ]
