# Generated by Django 4.2 on 2023-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_alter_boxmix_box_dessert_alter_boxmix_box_drink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
