# Generated by Django 4.2 on 2023-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_dish_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("Cart", "In Cart"), ("Sent", "Sent")], default=1
            ),
            preserve_default=False,
        ),
    ]
